### ISSUE TITLE
writting and reading json is not working yet

### ISSUE THREAD

**Issue by ThierryGibbons** [ThierryGibbons/Ordering-System#1]
cannot open source file "nlohmann/json.hpp"

**Comment by jazman43** [comment]
nlohmann/json.h is a header you must clone from github ive done this and added it as well as created a small class to mange files for us will still need tweaking as we go but main functionality is there.

**Comment by jazman43** [comment]
here is the link to the github repo you only need one file https://github.com/nlohmann/json
