### ISSUE TITLE
file checks

### ISSUE THREAD

**Issue by jazman43** [ThierryGibbons/Ordering-System#3]
i completey forgot to add a way to check all "id"s and display to user this id already exists this can be done later

**Comment by ThierryGibbons** [comment]
we dont need this just yet, just have it ping a default c++ file for the student id's and have that ping a null student id, i will write this section later, i can sort that dide of the code.

**Comment by jazman43** [comment]
ive add a function that takes a file path and a key the key being the json name for the id var like for order it's "orderID" this function will then check the last id number add 1 are return it if the json file is empty it will just return 1
